//
// AbuseStateConstant.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AbuseStateConstant: Codable {

    public var id: AbuseStateSet?
    public var label: String?

    public init(id: AbuseStateSet? = nil, label: String? = nil) {
        self.id = id
        self.label = label
    }

}
