//
// AbuseVideo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AbuseVideo: Codable {

    public var id: Int?
    public var name: String?
    public var uuid: UUID?

    public init(id: Int? = nil, name: String? = nil, uuid: UUID? = nil) {
        self.id = id
        self.name = name
        self.uuid = uuid
    }

}
