//
// AbuseMessage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AbuseMessage: Codable {

    public var id: Int?
    public var message: String?
    public var byModerator: Bool?
    public var createdAt: Date?
    public var account: AccountSummary?

    public init(id: Int? = nil, message: String? = nil, byModerator: Bool? = nil, createdAt: Date? = nil, account: AccountSummary? = nil) {
        self.id = id
        self.message = message
        self.byModerator = byModerator
        self.createdAt = createdAt
        self.account = account
    }

}
