//
// AbusesComment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AbusesComment: Codable {

    /** Comment id to report */
    public var id: Double?

    public init(id: Double? = nil) {
        self.id = id
    }

}
