//
// Abuse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Abuse: Codable {

    public enum PredefinedReasons: String, Codable, CaseIterable {
        case violentorabusive = "violentOrAbusive"
        case hatefulorabusive = "hatefulOrAbusive"
        case spamormisleading = "spamOrMisleading"
        case privacy = "privacy"
        case rights = "rights"
        case serverrules = "serverRules"
        case thumbnails = "thumbnails"
        case captions = "captions"
    }
    public var id: Int?
    public var reason: String?
    public var predefinedReasons: [PredefinedReasons]?
    public var reporterAccount: Account?
    public var state: AbuseStateConstant?
    public var moderationComment: String?
    public var video: AbuseVideo?
    public var createdAt: Date?

    public init(id: Int? = nil, reason: String? = nil, predefinedReasons: [PredefinedReasons]? = nil, reporterAccount: Account? = nil, state: AbuseStateConstant? = nil, moderationComment: String? = nil, video: AbuseVideo? = nil, createdAt: Date? = nil) {
        self.id = id
        self.reason = reason
        self.predefinedReasons = predefinedReasons
        self.reporterAccount = reporterAccount
        self.state = state
        self.moderationComment = moderationComment
        self.video = video
        self.createdAt = createdAt
    }

}
