//
// AccountAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AccountAllOf: Codable {

    public var userId: String?
    public var displayName: String?
    public var description: String?

    public init(userId: String? = nil, displayName: String? = nil, description: String? = nil) {
        self.userId = userId
        self.displayName = displayName
        self.description = description
    }

}
