//
// Actor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Actor: Codable {

    public var id: Int?
    public var url: String?
    public var name: String?
    public var host: String?
    public var followingCount: Int?
    public var followersCount: Int?
    public var createdAt: Date?
    public var updatedAt: Date?
    public var avatar: Avatar?

    public init(id: Int? = nil, url: String? = nil, name: String? = nil, host: String? = nil, followingCount: Int? = nil, followersCount: Int? = nil, createdAt: Date? = nil, updatedAt: Date? = nil, avatar: Avatar? = nil) {
        self.id = id
        self.url = url
        self.name = name
        self.host = host
        self.followingCount = followingCount
        self.followersCount = followersCount
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.avatar = avatar
    }

}
