//
// AddUserResponseUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddUserResponseUser: Codable {

    public var id: Int?
    public var account: AddUserResponseUserAccount?

    public init(id: Int? = nil, account: AddUserResponseUserAccount? = nil) {
        self.id = id
        self.account = account
    }

}
