//
// AddUserResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddUserResponse: Codable {

    public var user: AddUserResponseUser?

    public init(user: AddUserResponseUser? = nil) {
        self.user = user
    }

}
