//
// AddUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddUser: Codable {

    /** The user username */
    public var username: String
    /** The user password. If the smtp server is configured, you can leave empty and an email will be sent */
    public var password: String
    /** The user email */
    public var email: String
    /** The user video quota */
    public var videoQuota: Int
    /** The user daily video quota */
    public var videoQuotaDaily: Int
    /** The user default channel username */
    public var channelName: String?
    public var role: UserRole
    public var adminFlags: UserAdminFlags?

    public init(username: String, password: String, email: String, videoQuota: Int, videoQuotaDaily: Int, channelName: String? = nil, role: UserRole, adminFlags: UserAdminFlags? = nil) {
        self.username = username
        self.password = password
        self.email = email
        self.videoQuota = videoQuota
        self.videoQuotaDaily = videoQuotaDaily
        self.channelName = channelName
        self.role = role
        self.adminFlags = adminFlags
    }

}
