//
// Avatar.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Avatar: Codable {

    public var path: String?
    public var createdAt: Date?
    public var updatedAt: Date?

    public init(path: String? = nil, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.path = path
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

}
