//
// CommentThreadPostResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CommentThreadPostResponse: Codable {

    public var comment: VideoComment?

    public init(comment: VideoComment? = nil) {
        self.comment = comment
    }

}
