//
// FileRedundancyInformation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FileRedundancyInformation: Codable {

    public enum Strategy: String, Codable, CaseIterable {
        case manual = "manual"
        case mostViews = "most-views"
        case trending = "trending"
        case recentlyAdded = "recently-added"
    }
    public var id: Int?
    public var fileUrl: String?
    public var strategy: Strategy?
    public var size: Int?
    public var createdAt: Date?
    public var updatedAt: Date?
    public var expiresOn: Date?

    public init(id: Int? = nil, fileUrl: String? = nil, strategy: Strategy? = nil, size: Int? = nil, createdAt: Date? = nil, updatedAt: Date? = nil, expiresOn: Date? = nil) {
        self.id = id
        self.fileUrl = fileUrl
        self.strategy = strategy
        self.size = size
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.expiresOn = expiresOn
    }

}
