//
// Follow.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Follow: Codable {

    public enum State: String, Codable, CaseIterable {
        case pending = "pending"
        case accepted = "accepted"
    }
    public var id: Int?
    public var follower: Actor?
    public var following: Actor?
    /** score reflecting the reachability of the actor, with steps of &#x60;10&#x60; and a base score of &#x60;1000&#x60;. */
    public var score: Double?
    public var state: State?
    public var createdAt: Date?
    public var updatedAt: Date?

    public init(id: Int? = nil, follower: Actor? = nil, following: Actor? = nil, score: Double? = nil, state: State? = nil, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.id = id
        self.follower = follower
        self.following = following
        self.score = score
        self.state = state
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

}
