//
// GetMeVideoRating.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetMeVideoRating: Codable {

    /** Id of the video */
    public var id: String
    /** Rating of the video */
    public var rating: Double

    public init(id: String, rating: Double) {
        self.id = id
        self.rating = rating
    }

}
