//
// InlineResponse2001.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineResponse2001: Codable {

    public var total: Int?
    public var data: [VideoBlacklist]?

    public init(total: Int? = nil, data: [VideoBlacklist]? = nil) {
        self.total = total
        self.data = data
    }

}
