//
// InlineObject23.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineObject23: Codable {

    /** server domain to block */
    public var host: String

    public init(host: String) {
        self.host = host
    }

}
