//
// InlineObject11.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineObject11: Codable {

    public enum PredefinedReasons: String, Codable, CaseIterable {
        case violentorabusive = "violentOrAbusive"
        case hatefulorabusive = "hatefulOrAbusive"
        case spamormisleading = "spamOrMisleading"
        case privacy = "privacy"
        case rights = "rights"
        case serverrules = "serverRules"
        case thumbnails = "thumbnails"
        case captions = "captions"
    }
    /** Reason why the user reports this video */
    public var reason: String
    /** Reason categories that help triage reports */
    public var predefinedReasons: [PredefinedReasons]?
    public var video: AbusesVideo?
    public var comment: AbusesComment?
    public var account: AbusesAccount?

    public init(reason: String, predefinedReasons: [PredefinedReasons]? = nil, video: AbusesVideo? = nil, comment: AbusesComment? = nil, account: AbusesAccount? = nil) {
        self.reason = reason
        self.predefinedReasons = predefinedReasons
        self.video = video
        self.comment = comment
        self.account = account
    }

}
