//
// InlineObject21.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineObject21: Codable {

    /** Text comment */
    public var text: String

    public init(text: String) {
        self.text = text
    }

}
