//
// InlineObject17.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineObject17: Codable {

    /** Video to add in the playlist */
    public var videoId: Int
    /** Start the video at this specific timestamp (in seconds) */
    public var startTimestamp: Int?
    /** Stop the video at this specific timestamp (in seconds) */
    public var stopTimestamp: Int?

    public init(videoId: Int, startTimestamp: Int? = nil, stopTimestamp: Int? = nil) {
        self.videoId = videoId
        self.startTimestamp = startTimestamp
        self.stopTimestamp = stopTimestamp
    }

}
