//
// InlineResponse2004.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineResponse2004: Codable {

    public var total: Int?
    public var data: [VideoPlaylist]?

    public init(total: Int? = nil, data: [VideoPlaylist]? = nil) {
        self.total = total
        self.data = data
    }

}
