//
// InlineObject22.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineObject22: Codable {

    /** account to block, in the form &#x60;username@domain&#x60; */
    public var accountName: String

    public init(accountName: String) {
        self.accountName = accountName
    }

}
