//
// InlineObject13.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineObject13: Codable {

    /** Message to send */
    public var message: String

    public init(message: String) {
        self.message = message
    }

}
