//
// InlineObject2.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineObject2: Codable {

    /** ids of the notifications to mark as read */
    public var ids: [Int]

    public init(ids: [Int]) {
        self.ids = ids
    }

}
