//
// InlineObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineObject: Codable {

    public var hosts: Set<String>?

    public init(hosts: Set<String>? = nil) {
        self.hosts = hosts
    }

}
