//
// InlineResponse2007.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineResponse2007: Codable {

    public var videoId: [InlineResponse2007VideoId]?

    public init(videoId: [InlineResponse2007VideoId]? = nil) {
        self.videoId = videoId
    }

}
