//
// InlineObject25.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineObject25: Codable {

    public var videoId: Int

    public init(videoId: Int) {
        self.videoId = videoId
    }

}
