//
// InlineObject19.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineObject19: Codable {

    /** Start the video at this specific timestamp (in seconds) */
    public var startTimestamp: Int?
    /** Stop the video at this specific timestamp (in seconds) */
    public var stopTimestamp: Int?

    public init(startTimestamp: Int? = nil, stopTimestamp: Int? = nil) {
        self.startTimestamp = startTimestamp
        self.stopTimestamp = stopTimestamp
    }

}
