//
// InlineResponse2005VideoPlaylist.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineResponse2005VideoPlaylist: Codable {

    public var id: Int?
    public var uuid: String?

    public init(id: Int? = nil, uuid: String? = nil) {
        self.id = id
        self.uuid = uuid
    }

}
