//
// InlineObject27.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineObject27: Codable {

    public var settings: [String: Any]?

    public init(settings: [String: Any]? = nil) {
        self.settings = settings
    }

}
