//
// InlineObject1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineObject1: Codable {

    /** uri of the video channels to subscribe to */
    public var uri: String

    public init(uri: String) {
        self.uri = uri
    }

}
