//
// InlineObject12.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineObject12: Codable {

    public var state: AbuseStateSet?
    /** Update the report comment visible only to the moderation team */
    public var moderationComment: String?

    public init(state: AbuseStateSet? = nil, moderationComment: String? = nil) {
        self.state = state
        self.moderationComment = moderationComment
    }

}
