//
// InlineObject24.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineObject24: Codable {

    /** allow mirroring of the host&#39;s local videos */
    public var redundancyAllowed: Bool

    public init(redundancyAllowed: Bool) {
        self.redundancyAllowed = redundancyAllowed
    }

}
