//
// InlineResponse2003.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineResponse2003: Codable {

    public var total: Int?
    public var data: [VideoChannel]?

    public init(total: Int? = nil, data: [VideoChannel]? = nil) {
        self.total = total
        self.data = data
    }

}
