//
// InlineObject20.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineObject20: Codable {

    /** Text comment */
    public var text: String

    public init(text: String) {
        self.text = text
    }

}
