//
// InlineResponse2005.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineResponse2005: Codable {

    public var videoPlaylist: InlineResponse2005VideoPlaylist?

    public init(videoPlaylist: InlineResponse2005VideoPlaylist? = nil) {
        self.videoPlaylist = videoPlaylist
    }

}
