//
// InlineResponse2007VideoId.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineResponse2007VideoId: Codable {

    public var playlistElementId: Int?
    public var playlistId: Int?
    public var startTimestamp: Int?
    public var stopTimestamp: Int?

    public init(playlistElementId: Int? = nil, playlistId: Int? = nil, startTimestamp: Int? = nil, stopTimestamp: Int? = nil) {
        self.playlistElementId = playlistElementId
        self.playlistId = playlistId
        self.startTimestamp = startTimestamp
        self.stopTimestamp = stopTimestamp
    }

}
