//
// InlineResponse2006.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineResponse2006: Codable {

    public var videoPlaylistElement: InlineResponse2006VideoPlaylistElement?

    public init(videoPlaylistElement: InlineResponse2006VideoPlaylistElement? = nil) {
        self.videoPlaylistElement = videoPlaylistElement
    }

}
