//
// Job.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Job: Codable {

    public enum State: String, Codable, CaseIterable {
        case active = "active"
        case completed = "completed"
        case failed = "failed"
        case waiting = "waiting"
        case delayed = "delayed"
    }
    public enum ModelType: String, Codable, CaseIterable {
        case activitypubHttpUnicast = "activitypub-http-unicast"
        case activitypubHttpBroadcast = "activitypub-http-broadcast"
        case activitypubHttpFetcher = "activitypub-http-fetcher"
        case activitypubFollow = "activitypub-follow"
        case videoFileImport = "video-file-import"
        case videoTranscoding = "video-transcoding"
        case email = "email"
        case videoImport = "video-import"
        case videosViews = "videos-views"
        case activitypubRefresher = "activitypub-refresher"
        case videoRedundancy = "video-redundancy"
    }
    public var id: Int?
    public var state: State?
    public var type: ModelType?
    public var data: [String: Any]?
    public var error: [String: Any]?
    public var createdAt: Date?
    public var finishedOn: Date?
    public var processedOn: Date?

    public init(id: Int? = nil, state: State? = nil, type: ModelType? = nil, data: [String: Any]? = nil, error: [String: Any]? = nil, createdAt: Date? = nil, finishedOn: Date? = nil, processedOn: Date? = nil) {
        self.id = id
        self.state = state
        self.type = type
        self.data = data
        self.error = error
        self.createdAt = createdAt
        self.finishedOn = finishedOn
        self.processedOn = processedOn
    }

}
