//
// LiveVideoResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LiveVideoResponse: Codable {

    public var rtmpUrl: String?
    /** RTMP stream key to use to stream into this live video */
    public var streamKey: String?
    public var saveReplay: Bool?
    /** User can stream multiple times in a permanent live */
    public var permanentLive: Bool?

    public init(rtmpUrl: String? = nil, streamKey: String? = nil, saveReplay: Bool? = nil, permanentLive: Bool? = nil) {
        self.rtmpUrl = rtmpUrl
        self.streamKey = streamKey
        self.saveReplay = saveReplay
        self.permanentLive = permanentLive
    }

}
