//
// LiveVideoUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LiveVideoUpdate: Codable {

    public var saveReplay: Bool?
    /** User can stream multiple times in a permanent live */
    public var permanentLive: Bool?

    public init(saveReplay: Bool? = nil, permanentLive: Bool? = nil) {
        self.saveReplay = saveReplay
        self.permanentLive = permanentLive
    }

}
