//
// NotificationListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct NotificationListResponse: Codable {

    public var total: Int?
    public var data: [Notification]?

    public init(total: Int? = nil, data: [Notification]? = nil) {
        self.total = total
        self.data = data
    }

}
