//
// Notification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Notification: Codable {

    public var id: Int?
    /** Notification type, following the &#x60;UserNotificationType&#x60; enum: - &#x60;1&#x60; NEW_VIDEO_FROM_SUBSCRIPTION - &#x60;2&#x60; NEW_COMMENT_ON_MY_VIDEO - &#x60;3&#x60; NEW_ABUSE_FOR_MODERATORS - &#x60;4&#x60; BLACKLIST_ON_MY_VIDEO - &#x60;5&#x60; UNBLACKLIST_ON_MY_VIDEO - &#x60;6&#x60; MY_VIDEO_PUBLISHED - &#x60;7&#x60; MY_VIDEO_IMPORT_SUCCESS - &#x60;8&#x60; MY_VIDEO_IMPORT_ERROR - &#x60;9&#x60; NEW_USER_REGISTRATION - &#x60;10&#x60; NEW_FOLLOW - &#x60;11&#x60; COMMENT_MENTION - &#x60;12&#x60; VIDEO_AUTO_BLACKLIST_FOR_MODERATORS - &#x60;13&#x60; NEW_INSTANCE_FOLLOWER - &#x60;14&#x60; AUTO_INSTANCE_FOLLOWING  */
    public var type: Int?
    public var read: Bool?
    public var video: VideoInfo?
    public var videoImport: NotificationVideoImport?
    public var comment: NotificationComment?
    public var videoAbuse: NotificationVideoAbuse?
    public var videoBlacklist: NotificationVideoAbuse?
    public var account: ActorInfo?
    public var actorFollow: NotificationActorFollow?
    public var createdAt: Date?
    public var updatedAt: Date?

    public init(id: Int? = nil, type: Int? = nil, read: Bool? = nil, video: VideoInfo? = nil, videoImport: NotificationVideoImport? = nil, comment: NotificationComment? = nil, videoAbuse: NotificationVideoAbuse? = nil, videoBlacklist: NotificationVideoAbuse? = nil, account: ActorInfo? = nil, actorFollow: NotificationActorFollow? = nil, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.id = id
        self.type = type
        self.read = read
        self.video = video
        self.videoImport = videoImport
        self.comment = comment
        self.videoAbuse = videoAbuse
        self.videoBlacklist = videoBlacklist
        self.account = account
        self.actorFollow = actorFollow
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

}
