//
// NotificationActorFollowFollowing.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct NotificationActorFollowFollowing: Codable {

    public enum ModelType: String, Codable, CaseIterable {
        case account = "account"
        case channel = "channel"
        case instance = "instance"
    }
    public var type: ModelType?
    public var name: String?
    public var displayName: String?
    public var host: String?

    public init(type: ModelType? = nil, name: String? = nil, displayName: String? = nil, host: String? = nil) {
        self.type = type
        self.name = name
        self.displayName = displayName
        self.host = host
    }

}
