//
// PluginResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PluginResponse: Codable {

    public var total: Int?
    public var data: [Plugin]?

    public init(total: Int? = nil, data: [Plugin]? = nil) {
        self.total = total
        self.data = data
    }

}
