//
// Plugin.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Plugin: Codable {

    public enum ModelType: Int, Codable, CaseIterable {
        case _1 = 1
        case _2 = 2
    }
    public var name: String?
    /** - &#x60;1&#x60;: PLUGIN - &#x60;2&#x60;: THEME  */
    public var type: ModelType?
    public var latestVersion: String?
    public var version: String?
    public var enabled: Bool?
    public var uninstalled: Bool?
    public var peertubeEngine: String?
    public var description: String?
    public var homepage: String?
    public var settings: [String: Any]?
    public var createdAt: Date?
    public var updatedAt: Date?

    public init(name: String? = nil, type: ModelType? = nil, latestVersion: String? = nil, version: String? = nil, enabled: Bool? = nil, uninstalled: Bool? = nil, peertubeEngine: String? = nil, description: String? = nil, homepage: String? = nil, settings: [String: Any]? = nil, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.name = name
        self.type = type
        self.latestVersion = latestVersion
        self.version = version
        self.enabled = enabled
        self.uninstalled = uninstalled
        self.peertubeEngine = peertubeEngine
        self.description = description
        self.homepage = homepage
        self.settings = settings
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

}
