//
// RegisterUserChannel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RegisterUserChannel: Codable {

    /** The username for the default channel */
    public var name: String?
    /** The display name for the default channel */
    public var displayName: String?

    public init(name: String? = nil, displayName: String? = nil) {
        self.name = name
        self.displayName = displayName
    }

}
