//
// ServerConfigAbout.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigAbout: Codable {

    public var instance: ServerConfigAboutInstance?

    public init(instance: ServerConfigAboutInstance? = nil) {
        self.instance = instance
    }

}
