//
// ServerConfigCustomCache.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigCustomCache: Codable {

    public var previews: ServerConfigCustomCachePreviews?
    public var captions: ServerConfigCustomCachePreviews?

    public init(previews: ServerConfigCustomCachePreviews? = nil, captions: ServerConfigCustomCachePreviews? = nil) {
        self.previews = previews
        self.captions = captions
    }

}
