//
// ServerConfigCustomFollowersInstance.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigCustomFollowersInstance: Codable {

    public var enabled: Bool?
    public var manualApproval: Bool?

    public init(enabled: Bool? = nil, manualApproval: Bool? = nil) {
        self.enabled = enabled
        self.manualApproval = manualApproval
    }

}
