//
// ServerConfigVideoCaptionFile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigVideoCaptionFile: Codable {

    public var size: ServerConfigAvatarFileSize?
    public var extensions: [String]?

    public init(size: ServerConfigAvatarFileSize? = nil, extensions: [String]? = nil) {
        self.size = size
        self.extensions = extensions
    }

}
