//
// ServerConfigCustomSignup.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigCustomSignup: Codable {

    public var enabled: Bool?
    public var limit: Int?
    public var requiresEmailVerification: Bool?

    public init(enabled: Bool? = nil, limit: Int? = nil, requiresEmailVerification: Bool? = nil) {
        self.enabled = enabled
        self.limit = limit
        self.requiresEmailVerification = requiresEmailVerification
    }

}
