//
// ServerConfigCustomServicesTwitter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigCustomServicesTwitter: Codable {

    public var username: String?
    public var whitelisted: Bool?

    public init(username: String? = nil, whitelisted: Bool? = nil) {
        self.username = username
        self.whitelisted = whitelisted
    }

}
