//
// ServerConfigSearch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigSearch: Codable {

    public var remoteUri: ServerConfigSearchRemoteUri?

    public init(remoteUri: ServerConfigSearchRemoteUri? = nil) {
        self.remoteUri = remoteUri
    }

}
