//
// ServerConfigFollowingsInstance.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigFollowingsInstance: Codable {

    public var autoFollowIndex: ServerConfigFollowingsInstanceAutoFollowIndex?

    public init(autoFollowIndex: ServerConfigFollowingsInstanceAutoFollowIndex? = nil) {
        self.autoFollowIndex = autoFollowIndex
    }

}
