//
// ServerConfigFollowingsInstanceAutoFollowIndex.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigFollowingsInstanceAutoFollowIndex: Codable {

    public var indexUrl: String?

    public init(indexUrl: String? = nil) {
        self.indexUrl = indexUrl
    }

}
