//
// ServerConfigCustomTranscodingResolutions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigCustomTranscodingResolutions: Codable {

    public var _240p: Bool?
    public var _360p: Bool?
    public var _480p: Bool?
    public var _720p: Bool?
    public var _1080p: Bool?
    public var _1440p: Bool?
    public var _2160p: Bool?

    public init(_240p: Bool? = nil, _360p: Bool? = nil, _480p: Bool? = nil, _720p: Bool? = nil, _1080p: Bool? = nil, _1440p: Bool? = nil, _2160p: Bool? = nil) {
        self._240p = _240p
        self._360p = _360p
        self._480p = _480p
        self._720p = _720p
        self._1080p = _1080p
        self._1440p = _1440p
        self._2160p = _2160p
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _240p = "240p"
        case _360p = "360p"
        case _480p = "480p"
        case _720p = "720p"
        case _1080p = "1080p"
        case _1440p = "1440p"
        case _2160p = "2160p"
    }

}
