//
// ServerConfigCustomTheme.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigCustomTheme: Codable {

    public var _default: String?

    public init(_default: String? = nil) {
        self._default = _default
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _default = "default"
    }

}
