//
// ServerConfigFollowings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigFollowings: Codable {

    public var instance: ServerConfigFollowingsInstance?

    public init(instance: ServerConfigFollowingsInstance? = nil) {
        self.instance = instance
    }

}
