//
// ServerConfigCustomInstance.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigCustomInstance: Codable {

    public var name: String?
    public var shortDescription: String?
    public var description: String?
    public var terms: String?
    public var defaultClientRoute: String?
    public var isNSFW: Bool?
    public var defaultNSFWPolicy: String?
    public var customizations: ServerConfigInstanceCustomizations?

    public init(name: String? = nil, shortDescription: String? = nil, description: String? = nil, terms: String? = nil, defaultClientRoute: String? = nil, isNSFW: Bool? = nil, defaultNSFWPolicy: String? = nil, customizations: ServerConfigInstanceCustomizations? = nil) {
        self.name = name
        self.shortDescription = shortDescription
        self.description = description
        self.terms = terms
        self.defaultClientRoute = defaultClientRoute
        self.isNSFW = isNSFW
        self.defaultNSFWPolicy = defaultNSFWPolicy
        self.customizations = customizations
    }

}
