//
// ServerConfigSignup.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigSignup: Codable {

    public var allowed: Bool?
    public var allowedForCurrentIP: Bool?
    public var requiresEmailVerification: Bool?

    public init(allowed: Bool? = nil, allowedForCurrentIP: Bool? = nil, requiresEmailVerification: Bool? = nil) {
        self.allowed = allowed
        self.allowedForCurrentIP = allowedForCurrentIP
        self.requiresEmailVerification = requiresEmailVerification
    }

}
