//
// ServerConfigInstance.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigInstance: Codable {

    public var name: String?
    public var shortDescription: String?
    public var defaultClientRoute: String?
    public var isNSFW: Bool?
    public var defaultNSFWPolicy: String?
    public var customizations: ServerConfigInstanceCustomizations?

    public init(name: String? = nil, shortDescription: String? = nil, defaultClientRoute: String? = nil, isNSFW: Bool? = nil, defaultNSFWPolicy: String? = nil, customizations: ServerConfigInstanceCustomizations? = nil) {
        self.name = name
        self.shortDescription = shortDescription
        self.defaultClientRoute = defaultClientRoute
        self.isNSFW = isNSFW
        self.defaultNSFWPolicy = defaultNSFWPolicy
        self.customizations = customizations
    }

}
