//
// ServerConfigVideoFile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigVideoFile: Codable {

    public var extensions: [String]?

    public init(extensions: [String]? = nil) {
        self.extensions = extensions
    }

}
