//
// ServerConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfig: Codable {

    public var instance: ServerConfigInstance?
    public var search: ServerConfigSearch?
    public var plugin: ServerConfigPlugin?
    public var theme: ServerConfigPlugin?
    public var email: ServerConfigEmail?
    public var contactForm: ServerConfigEmail?
    public var serverVersion: String?
    public var serverCommit: String?
    public var signup: ServerConfigSignup?
    public var transcoding: ServerConfigTranscoding?
    public var _import: ServerConfigImport?
    public var autoBlacklist: ServerConfigAutoBlacklist?
    public var avatar: ServerConfigAvatar?
    public var video: ServerConfigVideo?
    public var videoCaption: ServerConfigVideoCaption?
    public var user: ServerConfigUser?
    public var trending: ServerConfigTrending?
    public var tracker: ServerConfigEmail?
    public var followings: ServerConfigFollowings?

    public init(instance: ServerConfigInstance? = nil, search: ServerConfigSearch? = nil, plugin: ServerConfigPlugin? = nil, theme: ServerConfigPlugin? = nil, email: ServerConfigEmail? = nil, contactForm: ServerConfigEmail? = nil, serverVersion: String? = nil, serverCommit: String? = nil, signup: ServerConfigSignup? = nil, transcoding: ServerConfigTranscoding? = nil, _import: ServerConfigImport? = nil, autoBlacklist: ServerConfigAutoBlacklist? = nil, avatar: ServerConfigAvatar? = nil, video: ServerConfigVideo? = nil, videoCaption: ServerConfigVideoCaption? = nil, user: ServerConfigUser? = nil, trending: ServerConfigTrending? = nil, tracker: ServerConfigEmail? = nil, followings: ServerConfigFollowings? = nil) {
        self.instance = instance
        self.search = search
        self.plugin = plugin
        self.theme = theme
        self.email = email
        self.contactForm = contactForm
        self.serverVersion = serverVersion
        self.serverCommit = serverCommit
        self.signup = signup
        self.transcoding = transcoding
        self._import = _import
        self.autoBlacklist = autoBlacklist
        self.avatar = avatar
        self.video = video
        self.videoCaption = videoCaption
        self.user = user
        self.trending = trending
        self.tracker = tracker
        self.followings = followings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case instance
        case search
        case plugin
        case theme
        case email
        case contactForm
        case serverVersion
        case serverCommit
        case signup
        case transcoding
        case _import = "import"
        case autoBlacklist
        case avatar
        case video
        case videoCaption
        case user
        case trending
        case tracker
        case followings
    }

}
