//
// ServerConfigCustom.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigCustom: Codable {

    public var instance: ServerConfigCustomInstance?
    public var theme: ServerConfigCustomTheme?
    public var services: ServerConfigCustomServices?
    public var cache: ServerConfigCustomCache?
    public var signup: ServerConfigCustomSignup?
    public var admin: ServerConfigCustomAdmin?
    public var contactForm: ServerConfigEmail?
    public var user: ServerConfigUser?
    public var transcoding: ServerConfigCustomTranscoding?
    public var _import: ServerConfigImport?
    public var autoBlacklist: ServerConfigAutoBlacklist?
    public var followers: ServerConfigCustomFollowers?

    public init(instance: ServerConfigCustomInstance? = nil, theme: ServerConfigCustomTheme? = nil, services: ServerConfigCustomServices? = nil, cache: ServerConfigCustomCache? = nil, signup: ServerConfigCustomSignup? = nil, admin: ServerConfigCustomAdmin? = nil, contactForm: ServerConfigEmail? = nil, user: ServerConfigUser? = nil, transcoding: ServerConfigCustomTranscoding? = nil, _import: ServerConfigImport? = nil, autoBlacklist: ServerConfigAutoBlacklist? = nil, followers: ServerConfigCustomFollowers? = nil) {
        self.instance = instance
        self.theme = theme
        self.services = services
        self.cache = cache
        self.signup = signup
        self.admin = admin
        self.contactForm = contactForm
        self.user = user
        self.transcoding = transcoding
        self._import = _import
        self.autoBlacklist = autoBlacklist
        self.followers = followers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case instance
        case theme
        case services
        case cache
        case signup
        case admin
        case contactForm
        case user
        case transcoding
        case _import = "import"
        case autoBlacklist
        case followers
    }

}
