//
// ServerConfigPlugin.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigPlugin: Codable {

    public var registered: [String]?

    public init(registered: [String]? = nil) {
        self.registered = registered
    }

}
