//
// ServerConfigCustomFollowers.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigCustomFollowers: Codable {

    public var instance: ServerConfigCustomFollowersInstance?

    public init(instance: ServerConfigCustomFollowersInstance? = nil) {
        self.instance = instance
    }

}
