//
// ServerConfigInstanceCustomizations.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigInstanceCustomizations: Codable {

    public var javascript: String?
    public var css: String?

    public init(javascript: String? = nil, css: String? = nil) {
        self.javascript = javascript
        self.css = css
    }

}
