//
// ServerConfigCustomAdmin.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigCustomAdmin: Codable {

    public var email: String?

    public init(email: String? = nil) {
        self.email = email
    }

}
