//
// ServerConfigAvatarFileSize.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigAvatarFileSize: Codable {

    public var max: Int?

    public init(max: Int? = nil) {
        self.max = max
    }

}
