//
// ServerConfigCustomCachePreviews.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigCustomCachePreviews: Codable {

    public var size: Int?

    public init(size: Int? = nil) {
        self.size = size
    }

}
