//
// ServerConfigCustomTranscoding.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigCustomTranscoding: Codable {

    public var enabled: Bool?
    public var allowAdditionalExtensions: Bool?
    public var allowAudioFiles: Bool?
    public var threads: Int?
    public var resolutions: ServerConfigCustomTranscodingResolutions?
    public var hls: ServerConfigEmail?

    public init(enabled: Bool? = nil, allowAdditionalExtensions: Bool? = nil, allowAudioFiles: Bool? = nil, threads: Int? = nil, resolutions: ServerConfigCustomTranscodingResolutions? = nil, hls: ServerConfigEmail? = nil) {
        self.enabled = enabled
        self.allowAdditionalExtensions = allowAdditionalExtensions
        self.allowAudioFiles = allowAudioFiles
        self.threads = threads
        self.resolutions = resolutions
        self.hls = hls
    }

}
