//
// ServerConfigTrendingVideos.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigTrendingVideos: Codable {

    public var intervalDays: Int?

    public init(intervalDays: Int? = nil) {
        self.intervalDays = intervalDays
    }

}
