//
// ServerConfigVideoImage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigVideoImage: Codable {

    public var extensions: [String]?
    public var size: ServerConfigAvatarFileSize?

    public init(extensions: [String]? = nil, size: ServerConfigAvatarFileSize? = nil) {
        self.extensions = extensions
        self.size = size
    }

}
