//
// ServerConfigTranscoding.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigTranscoding: Codable {

    public var hls: ServerConfigEmail?
    public var webtorrent: ServerConfigEmail?
    public var enabledResolutions: [Int]?

    public init(hls: ServerConfigEmail? = nil, webtorrent: ServerConfigEmail? = nil, enabledResolutions: [Int]? = nil) {
        self.hls = hls
        self.webtorrent = webtorrent
        self.enabledResolutions = enabledResolutions
    }

}
