//
// ServerConfigImport.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigImport: Codable {

    public var videos: ServerConfigImportVideos?

    public init(videos: ServerConfigImportVideos? = nil) {
        self.videos = videos
    }

}
