//
// ServerConfigSearchRemoteUri.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigSearchRemoteUri: Codable {

    public var users: Bool?
    public var anonymous: Bool?

    public init(users: Bool? = nil, anonymous: Bool? = nil) {
        self.users = users
        self.anonymous = anonymous
    }

}
