//
// ServerConfigUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigUser: Codable {

    public var videoQuota: Int?
    public var videoQuotaDaily: Int?

    public init(videoQuota: Int? = nil, videoQuotaDaily: Int? = nil) {
        self.videoQuota = videoQuota
        self.videoQuotaDaily = videoQuotaDaily
    }

}
