//
// ServerConfigAvatarFile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigAvatarFile: Codable {

    public var size: ServerConfigAvatarFileSize?

    public init(size: ServerConfigAvatarFileSize? = nil) {
        self.size = size
    }

}
