//
// ServerConfigCustomServices.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigCustomServices: Codable {

    public var twitter: ServerConfigCustomServicesTwitter?

    public init(twitter: ServerConfigCustomServicesTwitter? = nil) {
        self.twitter = twitter
    }

}
