//
// UpdateMe.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateMe: Codable {

    public enum DisplayNSFW: String, Codable, CaseIterable {
        case _true = "true"
        case _false = "false"
        case both = "both"
    }
    /** Your new password */
    public var password: String
    /** Your new email */
    public var email: String
    /** Your new displayNSFW */
    public var displayNSFW: DisplayNSFW
    /** Your new autoPlayVideo */
    public var autoPlayVideo: Bool

    public init(password: String, email: String, displayNSFW: DisplayNSFW, autoPlayVideo: Bool) {
        self.password = password
        self.email = email
        self.displayNSFW = displayNSFW
        self.autoPlayVideo = autoPlayVideo
    }

}
