//
// UserAdminFlags.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Admin flags for the user (None &#x3D; &#x60;0&#x60;, Bypass video blacklist &#x3D; &#x60;1&#x60;) */
public enum UserAdminFlags: Int, Codable, CaseIterable {
    case _0 = 0
    case _1 = 1
}
