//
// UserRole.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The user role (Admin &#x3D; &#x60;0&#x60;, Moderator &#x3D; &#x60;1&#x60;, User &#x3D; &#x60;2&#x60;) */
public enum UserRole: Int, Codable, CaseIterable {
    case _0 = 0
    case _1 = 1
    case _2 = 2
}
