//
// VideoFile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoFile: Codable {

    public var magnetUri: String?
    public var resolution: VideoResolutionConstant?
    /** Video file size in bytes */
    public var size: Int?
    public var torrentUrl: String?
    public var torrentDownloadUrl: String?
    public var fileUrl: String?
    public var fileDownloadUrl: String?
    public var fps: Double?
    public var metadataUrl: String?

    public init(magnetUri: String? = nil, resolution: VideoResolutionConstant? = nil, size: Int? = nil, torrentUrl: String? = nil, torrentDownloadUrl: String? = nil, fileUrl: String? = nil, fileDownloadUrl: String? = nil, fps: Double? = nil, metadataUrl: String? = nil) {
        self.magnetUri = magnetUri
        self.resolution = resolution
        self.size = size
        self.torrentUrl = torrentUrl
        self.torrentDownloadUrl = torrentDownloadUrl
        self.fileUrl = fileUrl
        self.fileDownloadUrl = fileDownloadUrl
        self.fps = fps
        self.metadataUrl = metadataUrl
    }

}
