//
// VideoRedundancy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoRedundancy: Codable {

    public var id: Int?
    public var name: String?
    public var url: String?
    public var uuid: UUID?
    public var redundancies: VideoRedundancyRedundancies?

    public init(id: Int? = nil, name: String? = nil, url: String? = nil, uuid: UUID? = nil, redundancies: VideoRedundancyRedundancies? = nil) {
        self.id = id
        self.name = name
        self.url = url
        self.uuid = uuid
        self.redundancies = redundancies
    }

}
