//
// VideoPlaylist.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoPlaylist: Codable {

    public var id: Int?
    public var createdAt: Date?
    public var updatedAt: Date?
    public var description: String?
    public var uuid: UUID?
    public var displayName: String?
    public var isLocal: Bool?
    public var videoLength: Int?
    public var thumbnailPath: String?
    public var privacy: VideoPlaylistPrivacyConstant?
    public var type: VideoPlaylistTypeConstant?
    public var ownerAccount: AccountSummary?
    public var videoChannel: VideoChannelSummary?

    public init(id: Int? = nil, createdAt: Date? = nil, updatedAt: Date? = nil, description: String? = nil, uuid: UUID? = nil, displayName: String? = nil, isLocal: Bool? = nil, videoLength: Int? = nil, thumbnailPath: String? = nil, privacy: VideoPlaylistPrivacyConstant? = nil, type: VideoPlaylistTypeConstant? = nil, ownerAccount: AccountSummary? = nil, videoChannel: VideoChannelSummary? = nil) {
        self.id = id
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.description = description
        self.uuid = uuid
        self.displayName = displayName
        self.isLocal = isLocal
        self.videoLength = videoLength
        self.thumbnailPath = thumbnailPath
        self.privacy = privacy
        self.type = type
        self.ownerAccount = ownerAccount
        self.videoChannel = videoChannel
    }

}
