//
// VideoImport.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoImport: Codable {

    public var id: Int?
    public var targetUrl: String?
    public var magnetUri: String?
    public var torrentName: String?
    public var state: VideoImportStateConstant?
    public var error: String?
    public var createdAt: Date?
    public var updatedAt: Date?
    public var video: Video?

    public init(id: Int? = nil, targetUrl: String? = nil, magnetUri: String? = nil, torrentName: String? = nil, state: VideoImportStateConstant? = nil, error: String? = nil, createdAt: Date? = nil, updatedAt: Date? = nil, video: Video? = nil) {
        self.id = id
        self.targetUrl = targetUrl
        self.magnetUri = magnetUri
        self.torrentName = torrentName
        self.state = state
        self.error = error
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.video = video
    }

}
