//
// VideoUserHistory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoUserHistory: Codable {

    public var currentTime: Int?

    public init(currentTime: Int? = nil) {
        self.currentTime = currentTime
    }

}
