//
// VideoPlaylistTypeConstant.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoPlaylistTypeConstant: Codable {

    public var id: VideoPlaylistTypeSet?
    public var label: String?

    public init(id: VideoPlaylistTypeSet? = nil, label: String? = nil) {
        self.id = id
        self.label = label
    }

}
