//
// VideoRating.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoRating: Codable {

    public var video: Video
    /** Rating of the video */
    public var rating: Double

    public init(video: Video, rating: Double) {
        self.video = video
        self.rating = rating
    }

}
