//
// VideoCommentThreadTree.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoCommentThreadTree: Codable {

    public var comment: VideoComment?
    public var children: [VideoCommentThreadTree]?

    public init(comment: VideoComment? = nil, children: [VideoCommentThreadTree]? = nil) {
        self.comment = comment
        self.children = children
    }

}
