//
// VideoUploadResponseVideo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoUploadResponseVideo: Codable {

    public var id: Int?
    public var uuid: UUID?

    public init(id: Int? = nil, uuid: UUID? = nil) {
        self.id = id
        self.uuid = uuid
    }

}
