//
// VideoStreamingPlaylists.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoStreamingPlaylists: Codable {

    public enum ModelType: Int, Codable, CaseIterable {
        case _1 = 1
    }
    public var id: Int?
    /** Playlist type (HLS &#x3D; &#x60;1&#x60;) */
    public var type: ModelType?
    public var playlistUrl: String?
    public var segmentsSha256Url: String?
    /** Video files associated to this playlist. The difference with the root \&quot;files\&quot; property is that these files are fragmented, so they can be used in this streaming playlist (HLS etc) */
    public var files: [VideoFile]?
    public var redundancies: [VideoStreamingPlaylistsRedundancies]?

    public init(id: Int? = nil, type: ModelType? = nil, playlistUrl: String? = nil, segmentsSha256Url: String? = nil, files: [VideoFile]? = nil, redundancies: [VideoStreamingPlaylistsRedundancies]? = nil) {
        self.id = id
        self.type = type
        self.playlistUrl = playlistUrl
        self.segmentsSha256Url = segmentsSha256Url
        self.files = files
        self.redundancies = redundancies
    }

}
