//
// VideoChannelCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoChannelCreate: Codable {

    public var name: String
    public var displayName: String
    public var description: String?
    /** A text shown by default on all videos of this channel, to tell the audience how to support it */
    public var support: String?

    public init(name: String, displayName: String, description: String? = nil, support: String? = nil) {
        self.name = name
        self.displayName = displayName
        self.description = description
        self.support = support
    }

}
