//
// VideoPrivacyConstant.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoPrivacyConstant: Codable {

    public var id: VideoPrivacySet?
    public var label: String?

    public init(id: VideoPrivacySet? = nil, label: String? = nil) {
        self.id = id
        self.label = label
    }

}
