//
// VideoChannelUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoChannelUpdate: Codable {

    public var displayName: String?
    public var description: String?
    /** A text shown by default on all videos of this channel, to tell the audience how to support it */
    public var support: String?
    /** Update the support field for all videos of this channel */
    public var bulkVideosSupportUpdate: Bool?

    public init(displayName: String? = nil, description: String? = nil, support: String? = nil, bulkVideosSupportUpdate: Bool? = nil) {
        self.displayName = displayName
        self.description = description
        self.support = support
        self.bulkVideosSupportUpdate = bulkVideosSupportUpdate
    }

}
