//
// VideoStreamingPlaylistsRedundancies.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoStreamingPlaylistsRedundancies: Codable {

    public var baseUrl: String?

    public init(baseUrl: String? = nil) {
        self.baseUrl = baseUrl
    }

}
