//
// VideoChannelSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoChannelSummary: Codable {

    public var id: Int?
    public var name: String?
    public var displayName: String?
    public var url: String?
    public var host: String?
    public var avatar: Avatar?

    public init(id: Int? = nil, name: String? = nil, displayName: String? = nil, url: String? = nil, host: String? = nil, avatar: Avatar? = nil) {
        self.id = id
        self.name = name
        self.displayName = displayName
        self.url = url
        self.host = host
        self.avatar = avatar
    }

}
