//
// VideoPlaylistPrivacySet.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The video playlist privacy (Public &#x3D; &#x60;1&#x60;, Unlisted &#x3D; &#x60;2&#x60;, Private &#x3D; &#x60;3&#x60;) */
public enum VideoPlaylistPrivacySet: Int, Codable, CaseIterable {
    case _1 = 1
    case _2 = 2
    case _3 = 3
}
