//
// VideoDetailsAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoDetailsAllOf: Codable {

    public var descriptionPath: String?
    /** A text tell the audience how to support the video creator */
    public var support: String?
    public var channel: VideoChannel?
    public var account: Account?
    public var tags: [String]?
    /** WebTorrent/raw video files. Can be empty if WebTorrent is disabled on the server. In this case, video files will be in the \&quot;streamingPlaylists[].files\&quot; property */
    public var files: [VideoFile]?
    public var commentsEnabled: Bool?
    public var downloadEnabled: Bool?
    public var trackerUrls: [String]?
    public var streamingPlaylists: [VideoStreamingPlaylists]?

    public init(descriptionPath: String? = nil, support: String? = nil, channel: VideoChannel? = nil, account: Account? = nil, tags: [String]? = nil, files: [VideoFile]? = nil, commentsEnabled: Bool? = nil, downloadEnabled: Bool? = nil, trackerUrls: [String]? = nil, streamingPlaylists: [VideoStreamingPlaylists]? = nil) {
        self.descriptionPath = descriptionPath
        self.support = support
        self.channel = channel
        self.account = account
        self.tags = tags
        self.files = files
        self.commentsEnabled = commentsEnabled
        self.downloadEnabled = downloadEnabled
        self.trackerUrls = trackerUrls
        self.streamingPlaylists = streamingPlaylists
    }

}
