//
// VideoPrivacySet.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The video privacy (Public &#x3D; &#x60;1&#x60;, Unlisted &#x3D; &#x60;2&#x60;, Private &#x3D; &#x60;3&#x60;, Internal &#x3D; &#x60;4&#x60;) */
public enum VideoPrivacySet: Int, Codable, CaseIterable {
    case _1 = 1
    case _2 = 2
    case _3 = 3
    case _4 = 4
}
