//
// VideoInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoInfo: Codable {

    public var id: Int?
    public var uuid: UUID?
    public var name: String?

    public init(id: Int? = nil, uuid: UUID? = nil, name: String? = nil) {
        self.id = id
        self.uuid = uuid
        self.name = name
    }

}
