//
// VideoResolutionConstant.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoResolutionConstant: Codable {

    /** Video resolution (240, 360, 720, 1080, 1440 or 2160) */
    public var id: Int?
    public var label: String?

    public init(id: Int? = nil, label: String? = nil) {
        self.id = id
        self.label = label
    }

}
