//
// VideoPlaylistPrivacyConstant.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoPlaylistPrivacyConstant: Codable {

    public var id: VideoPlaylistPrivacySet?
    public var label: String?

    public init(id: VideoPlaylistPrivacySet? = nil, label: String? = nil) {
        self.id = id
        self.label = label
    }

}
