//
// VideoScheduledUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoScheduledUpdate: Codable {

    public var privacy: VideoPrivacySet?
    /** When to update the video */
    public var updateAt: Date

    public init(privacy: VideoPrivacySet? = nil, updateAt: Date) {
        self.privacy = privacy
        self.updateAt = updateAt
    }

}
