//
// VideoChannel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoChannel: Codable {

    public var displayName: String?
    public var description: String?
    public var isLocal: Bool?
    public var ownerAccount: VideoChannelOwnerAccount?

    public init(displayName: String? = nil, description: String? = nil, isLocal: Bool? = nil, ownerAccount: VideoChannelOwnerAccount? = nil) {
        self.displayName = displayName
        self.description = description
        self.isLocal = isLocal
        self.ownerAccount = ownerAccount
    }

}
