//
// MySubscriptionsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class MySubscriptionsAPI {
    /**
     Get if subscriptions exist for my user
     
     - parameter uris: (query) list of uris to check if each is part of the user subscriptions 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func usersMeSubscriptionsExistGet(uris: [String], apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: Any?, _ error: Error?) -> Void)) {
        usersMeSubscriptionsExistGetWithRequestBuilder(uris: uris).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get if subscriptions exist for my user
     - GET /users/me/subscriptions/exist
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter uris: (query) list of uris to check if each is part of the user subscriptions 
     - returns: RequestBuilder<Any> 
     */
    open class func usersMeSubscriptionsExistGetWithRequestBuilder(uris: [String]) -> RequestBuilder<Any> {
        let path = "/users/me/subscriptions/exist"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String: Any]? = nil

        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "uris": uris.encodeToJSON(),
        ])

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Any>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Get my user subscriptions
     
     - parameter start: (query) Offset used to paginate results (optional)
     - parameter count: (query) Number of items to return (optional, default to 15)
     - parameter sort: (query) Sort column (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func usersMeSubscriptionsGet(start: Int? = nil, count: Int? = nil, sort: String? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) {
        usersMeSubscriptionsGetWithRequestBuilder(start: start, count: count, sort: sort).execute(apiResponseQueue) { result -> Void in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get my user subscriptions
     - GET /users/me/subscriptions
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter start: (query) Offset used to paginate results (optional)
     - parameter count: (query) Number of items to return (optional, default to 15)
     - parameter sort: (query) Sort column (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func usersMeSubscriptionsGetWithRequestBuilder(start: Int? = nil, count: Int? = nil, sort: String? = nil) -> RequestBuilder<Void> {
        let path = "/users/me/subscriptions"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String: Any]? = nil

        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "start": start?.encodeToJSON(),
            "count": count?.encodeToJSON(),
            "sort": sort?.encodeToJSON(),
        ])

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = OpenAPIClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Add subscription to my user
     
     - parameter inlineObject1: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func usersMeSubscriptionsPost(inlineObject1: InlineObject1? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) {
        usersMeSubscriptionsPostWithRequestBuilder(inlineObject1: inlineObject1).execute(apiResponseQueue) { result -> Void in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Add subscription to my user
     - POST /users/me/subscriptions
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter inlineObject1: (body)  (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func usersMeSubscriptionsPostWithRequestBuilder(inlineObject1: InlineObject1? = nil) -> RequestBuilder<Void> {
        let path = "/users/me/subscriptions"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: inlineObject1)

        let url = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = OpenAPIClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Delete subscription of my user
     
     - parameter subscriptionHandle: (path) The subscription handle 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func usersMeSubscriptionsSubscriptionHandleDelete(subscriptionHandle: String, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) {
        usersMeSubscriptionsSubscriptionHandleDeleteWithRequestBuilder(subscriptionHandle: subscriptionHandle).execute(apiResponseQueue) { result -> Void in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete subscription of my user
     - DELETE /users/me/subscriptions/{subscriptionHandle}
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter subscriptionHandle: (path) The subscription handle 
     - returns: RequestBuilder<Void> 
     */
    open class func usersMeSubscriptionsSubscriptionHandleDeleteWithRequestBuilder(subscriptionHandle: String) -> RequestBuilder<Void> {
        var path = "/users/me/subscriptions/{subscriptionHandle}"
        let subscriptionHandlePreEscape = "\(APIHelper.mapValueToPathItem(subscriptionHandle))"
        let subscriptionHandlePostEscape = subscriptionHandlePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{subscriptionHandle}", with: subscriptionHandlePostEscape, options: .literal, range: nil)
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String: Any]? = nil

        let url = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = OpenAPIClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Get subscription of my user
     
     - parameter subscriptionHandle: (path) The subscription handle 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func usersMeSubscriptionsSubscriptionHandleGet(subscriptionHandle: String, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: VideoChannel?, _ error: Error?) -> Void)) {
        usersMeSubscriptionsSubscriptionHandleGetWithRequestBuilder(subscriptionHandle: subscriptionHandle).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get subscription of my user
     - GET /users/me/subscriptions/{subscriptionHandle}
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter subscriptionHandle: (path) The subscription handle 
     - returns: RequestBuilder<VideoChannel> 
     */
    open class func usersMeSubscriptionsSubscriptionHandleGetWithRequestBuilder(subscriptionHandle: String) -> RequestBuilder<VideoChannel> {
        var path = "/users/me/subscriptions/{subscriptionHandle}"
        let subscriptionHandlePreEscape = "\(APIHelper.mapValueToPathItem(subscriptionHandle))"
        let subscriptionHandlePostEscape = subscriptionHandlePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{subscriptionHandle}", with: subscriptionHandlePostEscape, options: .literal, range: nil)
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String: Any]? = nil

        let url = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<VideoChannel>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     * enum for parameter nsfw
     */
    public enum Nsfw_usersMeSubscriptionsVideosGet: String, CaseIterable {
        case _true = "true"
        case _false = "false"
    }

    /**
     * enum for parameter filter
     */
    public enum Filter_usersMeSubscriptionsVideosGet: String, CaseIterable {
        case local = "local"
        case allLocal = "all-local"
    }

    /**
     * enum for parameter skipCount
     */
    public enum SkipCount_usersMeSubscriptionsVideosGet: String, CaseIterable {
        case _true = "true"
        case _false = "false"
    }

    /**
     * enum for parameter sort
     */
    public enum Sort_usersMeSubscriptionsVideosGet: String, CaseIterable {
        case name = "name"
        case duration = "-duration"
        case createdat = "-createdAt"
        case publishedat = "-publishedAt"
        case views = "-views"
        case likes = "-likes"
        case trending = "-trending"
        case hot = "-hot"
    }

    /**
     List videos of subscriptions of my user
     
     - parameter categoryOneOf: (query) category id of the video (see [/videos/categories](#tag/Video/paths/~1videos~1categories/get)) (optional)
     - parameter tagsOneOf: (query) tag(s) of the video (optional)
     - parameter tagsAllOf: (query) tag(s) of the video, where all should be present in the video (optional)
     - parameter licenceOneOf: (query) licence id of the video (see [/videos/licences](#tag/Video/paths/~1videos~1licences/get)) (optional)
     - parameter languageOneOf: (query) language id of the video (see [/videos/languages](#tag/Video/paths/~1videos~1languages/get)). Use &#x60;_unknown&#x60; to filter on videos that don&#39;t have a video language (optional)
     - parameter nsfw: (query) whether to include nsfw videos, if any (optional)
     - parameter filter: (query) Special filters which might require special rights:  * &#x60;local&#x60; - only videos local to the instance  * &#x60;all-local&#x60; - only videos local to the instance, but showing private and unlisted videos (requires Admin privileges)  * &#x60;all&#x60; - all videos, showing private and unlisted videos (requires Admin privileges)  (optional)
     - parameter skipCount: (query) if you don&#39;t need the &#x60;total&#x60; in the response (optional, default to ._false)
     - parameter start: (query) Offset used to paginate results (optional)
     - parameter count: (query) Number of items to return (optional, default to 15)
     - parameter sort: (query) Sort videos by criteria (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func usersMeSubscriptionsVideosGet(categoryOneOf: OneOfintegerarray? = nil, tagsOneOf: OneOfstringarray? = nil, tagsAllOf: OneOfstringarray? = nil, licenceOneOf: OneOfintegerarray? = nil, languageOneOf: OneOfstringarray? = nil, nsfw: Nsfw_usersMeSubscriptionsVideosGet? = nil, filter: Filter_usersMeSubscriptionsVideosGet? = nil, skipCount: SkipCount_usersMeSubscriptionsVideosGet? = nil, start: Int? = nil, count: Int? = nil, sort: Sort_usersMeSubscriptionsVideosGet? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: VideoListResponse?, _ error: Error?) -> Void)) {
        usersMeSubscriptionsVideosGetWithRequestBuilder(categoryOneOf: categoryOneOf, tagsOneOf: tagsOneOf, tagsAllOf: tagsAllOf, licenceOneOf: licenceOneOf, languageOneOf: languageOneOf, nsfw: nsfw, filter: filter, skipCount: skipCount, start: start, count: count, sort: sort).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List videos of subscriptions of my user
     - GET /users/me/subscriptions/videos
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter categoryOneOf: (query) category id of the video (see [/videos/categories](#tag/Video/paths/~1videos~1categories/get)) (optional)
     - parameter tagsOneOf: (query) tag(s) of the video (optional)
     - parameter tagsAllOf: (query) tag(s) of the video, where all should be present in the video (optional)
     - parameter licenceOneOf: (query) licence id of the video (see [/videos/licences](#tag/Video/paths/~1videos~1licences/get)) (optional)
     - parameter languageOneOf: (query) language id of the video (see [/videos/languages](#tag/Video/paths/~1videos~1languages/get)). Use &#x60;_unknown&#x60; to filter on videos that don&#39;t have a video language (optional)
     - parameter nsfw: (query) whether to include nsfw videos, if any (optional)
     - parameter filter: (query) Special filters which might require special rights:  * &#x60;local&#x60; - only videos local to the instance  * &#x60;all-local&#x60; - only videos local to the instance, but showing private and unlisted videos (requires Admin privileges)  * &#x60;all&#x60; - all videos, showing private and unlisted videos (requires Admin privileges)  (optional)
     - parameter skipCount: (query) if you don&#39;t need the &#x60;total&#x60; in the response (optional, default to ._false)
     - parameter start: (query) Offset used to paginate results (optional)
     - parameter count: (query) Number of items to return (optional, default to 15)
     - parameter sort: (query) Sort videos by criteria (optional)
     - returns: RequestBuilder<VideoListResponse> 
     */
    open class func usersMeSubscriptionsVideosGetWithRequestBuilder(categoryOneOf: OneOfintegerarray? = nil, tagsOneOf: OneOfstringarray? = nil, tagsAllOf: OneOfstringarray? = nil, licenceOneOf: OneOfintegerarray? = nil, languageOneOf: OneOfstringarray? = nil, nsfw: Nsfw_usersMeSubscriptionsVideosGet? = nil, filter: Filter_usersMeSubscriptionsVideosGet? = nil, skipCount: SkipCount_usersMeSubscriptionsVideosGet? = nil, start: Int? = nil, count: Int? = nil, sort: Sort_usersMeSubscriptionsVideosGet? = nil) -> RequestBuilder<VideoListResponse> {
        let path = "/users/me/subscriptions/videos"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String: Any]? = nil

        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "categoryOneOf": categoryOneOf?.encodeToJSON(),
            "tagsOneOf": tagsOneOf?.encodeToJSON(),
            "tagsAllOf": tagsAllOf?.encodeToJSON(),
            "licenceOneOf": licenceOneOf?.encodeToJSON(),
            "languageOneOf": languageOneOf?.encodeToJSON(),
            "nsfw": nsfw?.encodeToJSON(),
            "filter": filter?.encodeToJSON(),
            "skipCount": skipCount?.encodeToJSON(),
            "start": start?.encodeToJSON(),
            "count": count?.encodeToJSON(),
            "sort": sort?.encodeToJSON(),
        ])

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<VideoListResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

}
